(*
 * Alle Ressourcenstrings fangen mit "R_"  oder "RF_" an, so kann man direkt sehen das dieser Text Sprachabhängig ist.
 *
 * "R_" = Statischer Ressourcenstring
 * "RF_" = Ressourcentext, der via Format() noch Informationen geliefert bekommen muss.
 *)
Resourcestring

  R_Loading = 'Loading..';
  R_to_les_waypoints = 'To less waypoints.';
  R_NM_Logbook_Full = 'This geocacher reported that the logbook is full.';
  R_NM_Container_damaged = 'This geocacher reported that the container is damaged.';
  R_NM_Container_missing = 'This geocacher reported that the container is missing.';
  R_NM_Needs_Archive = 'This geocacher reported that the cache needs to be archieved.';
  R_NM_Other = 'This geocacher reported that the cache needs maintenance.';
  R_unknown = 'unknown';
  R_Attended = 'Attended';
  R_Will_attend = 'Will attend';
  R_Found_it = 'Found it';
  R_Webcam_photo_taken = 'Webcam photo taken';
  R_Did_not_find_it = 'Did not find it';
  R_Write_Note = 'Write note';
  R_Needs_Maintenance = 'Need maintenance';
  R_Needs_Archive = 'Needs archive';
  R_Container_Damaged = 'Container damaged';
  R_Logbook_full = 'Logbook full';
  R_Container_Missing = 'Container missing';
  R_Unattempted = 'Unattempted';
  R_Creating_Export_Script = 'This creates a export skript that exports the actual selection of caches to your GPS, edit the script with the script editor to add more features.';
  R_Welcome_Message = 'Welcome to CCM, after this dialog a setup wizard will help you to setup CCM for the daily use. You can restart the wizard via Help->Wizard';
  R_You_need_to_define_a_folder = 'You need to define a folder from within CCM can import .gpx/.zip files. This folder will also be used to download pocket queries and should normaly be empty.';
  R_No_Location_Name_defined = 'No location name defined.';
  R_you_did_not_install_the_ssl_library_downloading_logging_and_cache_preview_will_not_work = 'You did not install the SSL library downloading, logging and cache preview will not work. Download ccmsetup.zip or read the readme.txt file.';
  R_you_did_not_install_sqlite_ccm_will_not_work_download_ccmsetup_zip_or_read_the_readme_txt_file = 'You did not install SQLite3, CCM will not work. Download ccmsetup.zip or read the readme.txt file.';
  R_ccm_will_close_now = 'CCM will close now.';
  R_To_use_the_Groundspeak_Account_you_need_both_username_and_id = 'To use the groundspeak account you need both username and id';
  R_Do_you_want_to_edit_your_groundspeak_account_settings = 'Do you want to edit your groundspeak account settings (e.g. for online logging or pocket query downloading)?';
  R_Do_you_want_to_edit_the_logcounts_settings = 'Do you want to edit the logcounts settings?';
  R_Do_you_want_to_edit_distance_measurement_settings_for_caches = 'Do you want to edit distance measurement settings for caches?';
  R_Do_You_want_To_edit_a_GPS_settings = 'Do you want to edit GPS settings?';
  R_Do_You_want_To_edit_spoiler_downloading_settings = 'Do you want to edit spoiler downloading settings?';
  R_Wizard_finished_to_disable_go_to_the_Options_menu = 'Wizard finished, to disable go to the options menu.';
  R_Error_could_not_load_listing = 'Error could not load listing.';
  R_Enter_GC_Codes = 'Enter GC-Codes';
  R_Sum = 'Sum';
  R_average = 'average';
  R_Difficulty = 'difficulty';
  R_terrain = 'terrain';
  R_New_Query_Name = 'New query name';
  R_enter_new_title = 'Enter new title';
  R_Orig = 'orig';
  R_coordinate = 'Coordinate';
  R_Could_not_download_all_needed_files_abort_now = 'Could not download all needed files abort now.';
  R_Please_select_import_directory = 'Please select import directory';
  R_The_default_import_directory_was_not_set_yet_please_do_so_now = 'The default import directory was not set yet, please do so now.';
  R_found = 'found';
  R_Not_Found = 'not found';
  R_modified_coordinates = 'modified coordinates';
  R_Archived = 'Archived';
  R_Please_enter_a_filter_name = 'Please enter a filter name:';
  R_Already_in_list_double_click_image_to_remove = 'Already in list, double click image to remove.';
  R_Script_recursion_not_allowed = 'Script recursion not allowed.';
  R_OnYes = 'On Yes';
  R_OnNo = 'On No';
  R_Text = 'Text';
  R_Abort_Continue = 'Abort' + LineEnding + 'Continue';
  R_Script_name = 'Script name:';
  R_Enter_transaction_query = 'Enter transaction query:';
  R_Filter = 'Filter';
  R_Search = 'Search';
  R_Distance_km = 'Distance [km]';
  R_Do_not_import_found_caches = 'Do not import found caches';
  R_Delete_files_after_import = 'Delete files after import';
  R_Filename = 'Filename';
  R_Folder = 'Folder';
  R_Script_already_exists_enter_new_name_or_overwrite = 'Script already exists,' + LineEnding +
    'enter new name or overwrite:';
  R_Filter_already_exists_enter_new_name_or_overwrite = 'Filter already exists,' + LineEnding +
    'enter new name or overwrite:';
  R_TB_is_already_member_of_the_group = 'TB is already member of the group.';
  R_No_group_to_add_to = 'No group to add to.';
  R_No_group_to_delete_tb_from_to = 'No group to delete tb from to.';
  R_TB_is_not_in_group_can_not_delete = 'TB is not in group, can not delete.';
  R_TB_Code = 'TB-Code';
  R_Discovered = 'Discovered';
  R_Not_Existing = 'not existing';
  R_Not_discovered = 'not discovered';
  R_Not_yet_activated = 'not yet activated';
  R_locked = 'locked';
  R_Tools_Help = 'With the tools submenu you can integrate calls to external programs or homepages into the CCM mainmenu. Using the kind "Root Node" helps to organize the menu.';
  R_Incomplete_settings = 'Incomplete settings.';
  R_Error_while_adding_waypoint = 'Error while adding waypoint.';
  R_Error_while_parsing_waypoint = 'Error while parsing waypoint.';
  R_Could_not_decode = 'Could not decode.';
  R_Fav = 'Fav';
  R_You_do_not_have_that_many_favs_available_to_log = 'You do not have that many favourite points available to log.';
  R_Finished = 'Finished.';
  R_Database = 'Database';
  R_Not_In_Database = '- Not in database -'; // GC-Code kann nicht in DB gefunden werden, anstatt des Titels steht dann das hier da
  R_Customize = 'Customize'; // Der Text, der für die Custom Filter Query angezeigt wird ;)
  R_Type = 'Type';
  R_Type_DT = 'Type D/T';
  R_Code = 'Code';
  //R_km = 'km'; // -- Wir messen immer in km
  R_Title = 'Title';
  R_Cache = 'Cache: ';
  R_date = 'Date';
  R_State = 'State';
  R_problem = 'Problem';
  R_Image = 'Image';
  R_comment = 'Comment';
  R_Load = 'Load';
  R_Loaded = 'Loaded';
  R_Discover_Code = 'Discover-Code';
  R_Information = 'Information';
  R_Did_you_upload_the_geocache_visits_txt_to_www_geocaching_com_and_marked_as_logged_in_DB = 'Did you upload the geocache_visits.txt to www.geocaching.com and marked as logged in DB?';
  R_Warning = 'Warning';
  R_Warning_some_caches_where_not_in_database_Could_not_mark_all_caches_in_db = 'Warning, some caches where not in database. Could not mark all caches in database.';
  R_Question = 'Question';
  R_Enter_new_filter_name = 'Enter new filter name:';
  R_Select = 'Select';
  r_enter_search_text = 'Enter search text:';
  R_Not_Connected = 'Not connected';
  R_Noting_Selected = 'Nothing selected.';
  R_You_have_not_selected_all_entries_the_missing_ones_are_not_exported = 'You have not selected all entries, the missing ones are not exported.';
  R_None = 'None';
  R_No_Script_name_defined = 'No Script name defined.';
  R_Error_could_not_set_index_restart_application_and_double_check_all_values = 'Error could not set index, restart application and double check all values.';
  R_Delete_Database_can_not_be_undone = 'Deleting the actual database can not be undone, are you shure you want to delete the database?';
  R_clear_temp_folder_before_download = 'clear temp folder before download';
  R_No_Import_Folder_Set = 'No Import folder set, please define import folder in the "File and folder editor" or in the "Import directory" dialog.';
  R_Could_not_Download_valid_Version_Information = 'Could not download valid version information for CCM.';
  R_Unable_to_create_workdir = 'Unable to create workdir, cancel now.';
  R_Starting = 'Starting..';
  R_Starting_update_please_wait = 'Starting update, please wait.';
  R_Your_Version_is_up_to_date = 'Your version is up to date, nothing to do.';
  R_No_Logs_found_in_List = 'No logs found in list.';
  R_CCM_User_Note = '-- CCM user note --';
  R_CCM_End_User_Note = '-- End CCM user note --';
  R_Process_aborted = 'Process aborted.';
  R_Export_Spoilers = 'Export Spoilers';
  R_No_file_to_save_selected_abort_now = 'No file to save selected, abort now.';
  R_No_database_selected_abort_script = 'No database selected, abort script.';
  R_No_directory_selected_abort_script = 'No directory selected, abort script.';
  R_SQL_Admin_Warning = 'You are opening the SQL Admin tool, this is for experienced user only, ' +
    'there is no fallback, or other error checks. You are on your on risk.' + LineEnding +
    'Press no if you are not shure.';
  R_All_Shown_Caches_have_not_been_updated_mar_as_archived = 'All shown caches have not been updated, should they be marked as archived?';
  R_Get_Spoilers = 'Get Spoilers';
  R_To_use_this_feature_select_only_one_cache = 'To use this feature select only one cache.';
  R_Store_Plain_Passwort_Warning = 'Storing passwords in plain text is risky and unsave, everyone that can open this application will be able to read your password. Do you really want to store your password?';
  R_No_geocaching_username_defined_go_to_the_options_to_define_abort_now = 'No geocaching username defined (go to the options to define), abort now.';
  R_Password_required = 'Password required';
  R_Please_enter_geocaching_online_password = 'Please enter geocaching online password';
  R_Please_enter_proxy_password = 'Please enter proxy password';
  R_No_valid_password_abort_now = 'No valid password, abort now.';
  R_Proxy_settings_changed_please_save_options_first_and_then_try_again = 'Proxy settings changed, please save options first and then try again.';
  R_Please_save_and_restart_the_application_to_apply_language_changes = 'Please save and restart the application to apply language changes.';
  R_Cache_not_in_database_use_the_open_cache_in_browser_feature = 'Cache not in database, use the open cache in browser feature.';
  R_Labcache_Warning = 'You tried to store Lab Caches to the fieldnote file, they can not be logged on geocaching.com, so they where skipped.' + LineEnding +
    'Go to https://labs.geocaching.com/ and log them manually.';
  R_You_Tried_To_Log_Labcaches = 'You tried to log Lab Caches online, they can not be logged on geocaching.com, so they where skipped.' + LineEnding +
    'Go to https://labs.geocaching.com/ and log them manually.';
  R_Enter_log_text = 'Enter log text';
  R_No_TB_Codes_entered = 'No TB-Codes entered.';
  R_Total = 'Total';
  R_Please_clear_cache_for_maptiles = 'Please clear the cache for maptiles to reload all maps in selected language.';
  R_Usernote_from_database = 'Usernote from database';
  R_Online_Usernote = 'Online usernote';
  R_Append_db_note_to_online = 'Append db note to online';
  R_Append_online_note_to_db = 'Append online note to db';
  R_Replace_db_note_by_online = 'Replace db note by online';
  R_Modified_coordinate_from_database = 'Modified coordinate from database';
  R_Modified_coordinate_from_website = 'Modified coordinate from website';
  R_No_Change = 'no change';
  R_Replace_with_online_version = 'replace with online version';
  R_Replace_with_db_version = 'replace with db version';
  R_Note_To_long = 'Note to long';

  R_Error_This_feature_is_only_available_if_you_have_a_premium_account = 'Error: this feature is only available if you have a premium account.';
  R_Error_Length_of_UserNote_is_to_Long = 'Error: Length of usernote is to long.';
  R_Error_you_have_to_download_the_cache_first = 'Error: You have to download the cache first.';
  R_Error_You_have_to_select_at_least_deg_or_dec_coordinates_to_support_parking_area_coord_export = 'Error, you have to select at least deg or dec coordinates to support parking area coord export.';
  R_Error_No_valid_input = 'Error, no valid input.';
  R_Error_no_gpsbabel_folder_set = 'Error, no GPSBabel folder set.';
  R_Error_could_not_discover_all_TBs_see_table = 'Error could not discover all TB''s, see table.';
  R_Error_not_connected_to_database = 'Error: not connected to database.';
  R_Error_unable_to_copy_file = 'Error: unable to copy file.';
  R_Error_invalid_ggz_filename = 'Error: invalid GGZ filename';
  R_Error_no_caches_for_export_selected = 'Error: no caches for export selected.';
  R_Error_while_creating_Waypointlist = 'Error: while creating Waypointlist.';
  R_Error_invalid_input_nothing_changed = 'Error: invalid input, nothing changed.';
  R_Error_no_other_databases_found_Please_create_one_first = 'Error: no other databases found. Please create one first.';
  R_Error_invalid_POI_folder = 'Error: invalid POI folder';
  R_Error_Could_not_create_POI_folder = 'Error: Could not create POI folder';
  R_Error_Could_not_create_GPI = 'Error: Could not create .gpi file, did you install gpsbabel?' + LineEnding +
    '[Windows user only]' + LineEnding +
    'If you do not add gpsbabel to your environment path, you have to set its folder in the options dialog.';
  R_Error_could_not_log_when_username_and_userid_is_not_set = 'Error could not log, when username or userid is not set.';
  R_Error_could_not_init_dglOpenGL_pas = 'Error, could not init dglOpenGL.pas';
  R_error_no_Name_defined = 'Error, no name defined.';
  R_Error_trackable_code_has_to_begin_with_TB = 'Error, trackable code has to begin with TB';

  // ---------- Ab hier Ressourcenstrings für format ----------

  RF_Default_value_for_filter_changed_do_you_want_to_apply_the_new_default_value = 'Default value for filter "%s" changed, do you want to apply the new default value ?';
  RF_Error_could_not_find_default_value_for = 'Error, could not find default value for: %s';
  RF_The_Following_Caches_have_had_Errors_during_Upload_Please_Check = 'The following caches have had errors during upload %s.' + LineEnding + 'Please check by hand.';
  RF_Edit_Usernote_for = 'Edit usernote for %s';
  RF_Edit_modified_Coords_for = 'Edit modified coordinates for %s';
  RF_Edit_listing = 'Edit listing of: %s';
  RF_Logs_for = '%d logs for: %s';
  Rf_You_changed_databasefolder = 'You changed the database folder from "%s" to "%s" please copy existing databases by hand into the new folder, otherwise they could not be loaded anymore';
  RF_Archived_caches_could_not_be_updated = '%d archived caches could not be updated.';
  RF_error_already_exists = 'Error, "%s" already exists.';
  RF_Activating_Download_in_Zoom_lt_could_cause_havy_download_times = 'Activating the download function in zoom levels less or equal %d could cause huge download times and massive lags, are you shure?';
  RF_Your_Query_results_in_datasets = 'Your query results in %d datatsets.';
  RF_eg_time = 'e.g.: %s (%%.%%.2019 = all in 2019)';
  RF_Waypoint_with_title_already_exists = 'Waypoint with title "%s" already exists.';
  RF_can_not_find_Waypoint_with_title = 'Can not find waypoint with title "%s"';
  RF_Could_not_find_Cache_info_for = 'Could not find Cache info for: %s';
  RF_The_following_TBs_are_ignored_they_are_already_in_the_list = 'The following TB''s are ignored, they are already in the list: %s';
  RF_Discovering_a_TB_with_no_comment_will_fail_Please_unselect_or_write_a_comment = 'Discovering a TB[%s], with no comment, will fail. Please unselect or write a comment.';
  RF_Details_of = 'Details of %s %s';
  RF_Your_query_results_in_caches = 'Your query results in %s caches.';
  RF_Value_not_Allowd = 'Value: %s not allowed.';
  RF_Delete_Filter_Will_Fail_Script = 'Deleting the filter: %s' + LineEnding +
    'will leave the script: %s' + LineEnding +
    'in a invalid state.' + LineEnding + LineEnding +
    'Do you really want to delete the filter %s?';
  RF_Could_not_locate_Query = 'Could not locate query: %s' + LineEnding +
    'Did you really added it first?';
  RF_Could_not_locate_tool_Did_you_really_added_it_first = 'Could not locate tool: %s' + LineEnding +
    'Did you really added it first?';
  RF_Sucessfully_logged_in_Your_online_found_number_is = 'Sucessfully logged in.' + LineEnding + 'Your online found number is: %d';
  RF_Refresh_Found_Number = 'Your actual local found number is: %s' + LineEnding +
    'Your online found number is: %d' + LineEnding +
    'Do you want to apply %d as your new local found number?';
  RF_Unable_to_extract_find_count = 'Unable to extract find count: ' + LineEnding + '%s';
  RF_Could_not_log_in_Error = 'Could not log in.' + LineEnding + 'Error:' + LineEnding + '%s';
  RF_Delete = 'Delete: %s';
  RF_Imported_Caches_in = 'Imported %d caches in %s';
  RF_Downloaded_spoiler_images_Time = 'Downloaded spoiler images: %d' + LineEnding + 'Time: %s';
  RF_Skipped_caches_due_to_invalid_d_t_settings = 'Skipped %d caches due to invalid d / t settings.';
  RF_Skipped_caches_as_the_date_lies_in_the_future = 'Skipped %d caches as the date lies in the future.';
  RF_Skipped_labcaches = 'Skipped %d Lab Caches';
  RF_Script_finished_in = 'Script finished in %s';
  RF_Finished_after = 'Finished, in: %s';
  RF_Database_already_exist_overwrite = 'Database: "%s" already exist, overwrite?';
  RF_Caches = 'Caches: %d';
  RF_Time = 'Time %s';
  RF_Create = 'Create: %s';
  RF_Edit_Note = 'Edit note: %s';
  RF_Hint = 'Hint: %s';
  RF_Connected_To = 'Connected to: %s';
  RF_Could_Not_Load = 'unable to load db: %s';
  RF_VersionInfo = 'Your version: %s' + LineEnding +
    'Online version: %s' + LineEnding +
    'Release Message: ' + LineEnding + LineEnding + '%s' + LineEnding + LineEnding +
    'If you start the update now, all unsaved data will get lost.' + LineEnding +
    'Would you like to update CCM now?';
  RF_An_Error_Occured = 'An error occured, the update process is not finished correct:' + LineEnding + LineEnding +
    '%s' + LineEnding + LineEnding +
    'Please retry by hand (or retry with admin rights).';
  RF_Visits_Editor_found = 'Geocache visits editor, %d visits found.';
  RF_caches_already_found_change_to_write_note = 'The caches "%s" are already marked es found, change the logstate to "write note"';
  RF_Attention_Double_Caches = 'Attention, the caches:' + LineEnding + '%s are more than once in the list. Please double check.';
  RF_Changed_State_To = 'Changed state "%s" to "%s" or "%s" on:' + LineEnding + '%s';
  RF_Logdate_Not_From_Today = 'The cache: %s do not have a logdate from today, is this correct?';
  RF_Database_exists_replace = 'Database "%s" already exists, replace with a empty one?';
  RF_Nothing_imported_from_abort_script = 'Nothing imported from "%s", abort script now.';
  RF_Error_in_Script_on_Load = 'Error in script: %s' + LineEnding +
    'On command "load database", aborting now, leaving program in invalid state.';
  RF_Error_in_Script_on_Copy = 'Error in script: %s' + LineEnding +
    'on command "copy selection to other database", aborting now, leaving in invalid state.';
  RF_Error_in_Script_on_Move = 'Error in script: %s' + LineEnding +
    'on command "move selection to other database", aborting now, leaving in invalid state.';
  RF_Error_in_Script_on_ExportPQ = 'Error in script: %s' + LineEnding +
    'on command "Export as pocketquery", aborting now, leaving in invalid state.';
  RF_Error_in_Script_on_Export_GPX = 'Error in script: %s' + LineEnding +
    'on command "Export as GSAK", aborting now, leaving in invalid state.';
  RF_Error_in_Script_on_Expor_GGZ = 'Error in script: %s' + LineEnding +
    'on command "export as GGZ", aborting now, leaving in invalid state.';
  RF_Error_in_Script_on_Expor_POI = 'Error in script: %s' + LineEnding +
    'on command "export as POI", aborting now, leaving in invalid state.';
  RF_Unable_Create_Script = 'Unable to create "%s"' + LineEnding +
    'aborting now, leaving program in invalid state.';
  RF_Unable_Create_From_Script = 'Unable to create database from "%s"' + LineEnding +
    'aborting now, leaving program in invalid state.';
  RF_Error_could_not_delete_Script = 'Error could not delete database "%s"' + LineEnding +
    'aborting now, leaving program in invalid state.';
  RF_Unable_Get_Cut_Set_Script = 'Unable to get cut set to database "%s"' + LineEnding +
    'aborting now, leaving program in invalid state.';
  RF_Not_implemented_abord_now = 'Not implemented function "%s" abort now.';
  RF_The_folder_is_not_in_the_export_add = 'The folder:' + LineEnding + LineEnding + '%s' + LineEnding + LineEnding + 'is not in the export POI to list, do you want to add it now?';
  RF_Could_not_resolve_container_size = 'Could not resolve container size: %s';
  RF_Deleting_Location = 'Deleting the location: %s' + LineEnding +
    'will disable the distance calculations for all caches.' + LineEnding + LineEnding +
    'Do you really want to delete the location %s?';
  RF_Deleting_the_script_will_leave_invalid_state = 'Deleting the script: %s' + LineEnding +
    'will leave the script: %s' + LineEnding +
    'in a invalid state.' + LineEnding + LineEnding +
    'Do you really want to delete the script %s?';
  RF_Filter_already_exists_overwrite_it = 'Filter "%s" already exists, overwrite it?';
  RF_The_Caches_are_missing_in_database_redownload_them = 'The caches "%s" are not in the database, download them now?';
  RF_The_Caches_Are_Lite_Caches_redownload_them = 'The caches "%s" are lite caches, download them now?';
  RF_unable_to_redownload_caches = 'Unable to download/import the caches "%s".';
  RF_Finished_deleted_files = 'Finished, deleted %d files.';

  RF_Could_not_Open_Or_Create_Database_Did_you_install_SQLite3 = 'Could not open or create database "%s" did you instal sqlite3?';
  RF_Could_not_locate_location_Did_you_really_added_it_first = 'Could not locate location: %s' + LineEnding +
    'Did you really added it first?';
  RF_OpenGLError = 'OpenGL Error (%d) occured.' + LineEnding + LineEnding +
    'OpenGL Message: "%s"' + LineEnding + LineEnding +
    'Applikation will be terminated.';
  RF_Attention_the_Caches_are_only_write_notes = 'Attention, the caches %s are only write notes.';
  RF_Attention_the_Caches_will_be_logged_as_write_notes = 'Attention, the caches %s will be logged as write notes.';
  RF_Error_Favs_only_for_found_and_webcam_photo_taken_allowed = 'Error: Favs only allowed on found it or webcam photo taken logs' + LineEnding + '%s';
  RF_Error_could_not_export_section = 'Error, could not export section: %s';
  RF_Error = 'Error: %s';
  RF_Error_Directory_does_not_exist = 'Error: Directory does not exist: %s';
  RF_Error_could_not_load_userpoints_imageOpenGL_Errorcode = 'Error could not load userpoints image: %s' + LineEnding +
    'OpenGL Errorcode: %d= (%s)';
  RF_Error_unable_to_decode_location = 'Error, unable to decode location: %s %s';
  RF_Error_no_logtext_for = 'Error: No log text for: %s';
  RF_Error_to_long_logtext_for = 'Error: To long logtext for: %s';
  RF_Error_could_not_find = 'Error: could not find: %s';
  RF_Error_could_not_delete = 'Error: could not delete: %s';
  RF_Error_could_not_create = 'Error: could not create: %s';
  RF_Error_could_not_Connect = 'Error: could not connect.' + LineEnding + 'Errormessage:' + LineEnding + '%s';
  RF_Error_invalid_value_for_CachesPerGPXContainer = 'Error: invalid value for CachesPerGPXContainer: %s';
  RF_Error_invalid_Query = 'Error: invalid query' + LineEnding + 'Error message:' + LineEnding + '%s';
  RF_Error_category_not_exported = 'Error: category "%s" was not exported.';
  RF_Error_You_Selected_invalid_logs = 'You selected invalid logs (missing logdate, logstate, gccode), import will fail:' + LineEnding + LineEnding +
    '%s' + LineEnding + LineEnding +
    'Please revisit the named caches and correct them, they have been unselected.';
  RF_Error_Could_Not_import = 'Error: could not import caches: %s';
  RF_Error_Could_Not_Download = 'Error: could not download GPX-files for: %s';
  RF_Error_Could_Not_Download_and_not_import = 'Error: could not download GPX-files for: %s' + LineEnding + 'could not import caches: %s';
  RF_warning_File_does_not_exist = 'Warning: the file %s does not exist';

