(******************************************************************************)
(*                                                                            *)
(* Author      : Uwe Schächterle (Corpsman)                                   *)
(*                                                                            *)
(* This file is part of CCM                                                   *)
(*                                                                            *)
(*  See the file license.md, located under:                                   *)
(*  https://github.com/PascalCorpsman/Software_Licenses/blob/main/license.md  *)
(*  for details about the license.                                            *)
(*                                                                            *)
(*               It is not allowed to change or remove this text from any     *)
(*               source file of the project.                                  *)
(*                                                                            *)
(******************************************************************************)

// Use if you want to use the Tokenizer from www.Corpsman.de
{$DEFINE UseTokenizer}

// Use OOP Callbacks for operands
{.$DEFINE OOP_Callbacks}

// Give the ability to render the calculation tree on a canvas
{.$define ALLOW_RENDERTREE}

// Use Binary operands left and right sided.
{.$define Beidseitig}


