(******************************************************************************)
(*                                                                            *)
(* Author      : Uwe Schächterle (Corpsman)                                   *)
(*                                                                            *)
(* This file is part of CCM                                                   *)
(*                                                                            *)
(*  See the file license.md, located under:                                   *)
(*  https://github.com/PascalCorpsman/Software_Licenses/blob/main/license.md  *)
(*  for details about the license.                                            *)
(*                                                                            *)
(*               It is not allowed to change or remove this text from any     *)
(*               source file of the project.                                  *)
(*                                                                            *)
(******************************************************************************)

Const

  updater_Version = '2.52';

  updater_AppName = 'ccm';
  updater_StarterName = 'ccm';
  updater_UpdaterName = 'updater';
  updater_DownloadLink = 'https://corpsman.de/klickcounter.php?url=download/ccm.zip';
  updater_Additional = 'release_text_de'; // Liste der Potenziellen weiteren Datenfelder alle durch , getrennt.

